server:
  port: 8082
spring:
  application:
    name: consumer-order
  security:
    user:
      name: eureka
      password: 123456
#链路追踪
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://39.108.65.199:9411/

eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://eureka:123456@127.0.0.1:8761/eureka


#开启使用hystrix熔断器
feign:
  hystrix:
    enabled: true

#设置断路器超时时间，默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #断路器超时时间，默认1000ms
            timeoutInMilliseconds: 3000

#全局日志  
logging:
  level:
    root: debug



    